//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// JSONMessage defines model for JSONMessage.
type JSONMessage struct {
	Message *string `json:"message,omitempty"`
}

// Order defines model for Order.
type Order struct {
	Amount   *int                `json:"amount,omitempty"`
	Bid      *bool               `json:"bid,omitempty"`
	Currency *string             `json:"currency,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	Premium  *int                `json:"premium,omitempty"`
}

// OrderArray defines model for OrderArray.
type OrderArray = []struct {
	Schema *Order `json:"schema,omitempty"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	Sort   *string `form:"sort,omitempty" json:"sort,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = Order

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /orders)
	GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams)

	// (POST /orders)
	PostOrders(w http.ResponseWriter, r *http.Request)

	// (DELETE /orders/{order-id})
	DeleteOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (GET /orders/{order-id})
	GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (DELETE /orders/{order-id}/trade)
	DeleteOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (GET /orders/{order-id}/trade)
	GetOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (POST /orders/{order-id}/trade)
	PostOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (DELETE /orders/{order-id}/trade/escrow)
	DeleteOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (GET /orders/{order-id}/trade/escrow)
	GetOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (POST /orders/{order-id}/trade/escrow)
	PostOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (DELETE /orders/{order-id}/trade/escrow/dispute)
	DeleteOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (POST /orders/{order-id}/trade/escrow/dispute)
	PostOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)

	// (POST /token/generate)
	PostTokenGenerate(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrdersOrderId operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrdersOrderId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrdersOrderId(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersOrderId operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersOrderId(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrdersOrderIdTrade operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrdersOrderIdTrade(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersOrderIdTrade operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersOrderIdTrade(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersOrderIdTrade operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersOrderIdTrade(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrdersOrderIdTradeEscrow operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrdersOrderIdTradeEscrow(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersOrderIdTradeEscrow operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersOrderIdTradeEscrow(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersOrderIdTradeEscrow operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersOrderIdTradeEscrow(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrdersOrderIdTradeEscrowDispute operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrdersOrderIdTradeEscrowDispute(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersOrderIdTradeEscrowDispute operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order-id" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "order-id", r.PathValue("order-id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersOrderIdTradeEscrowDispute(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTokenGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostTokenGenerate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTokenGenerate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/orders", wrapper.GetOrders)
	m.HandleFunc("POST "+options.BaseURL+"/orders", wrapper.PostOrders)
	m.HandleFunc("DELETE "+options.BaseURL+"/orders/{order-id}", wrapper.DeleteOrdersOrderId)
	m.HandleFunc("GET "+options.BaseURL+"/orders/{order-id}", wrapper.GetOrdersOrderId)
	m.HandleFunc("DELETE "+options.BaseURL+"/orders/{order-id}/trade", wrapper.DeleteOrdersOrderIdTrade)
	m.HandleFunc("GET "+options.BaseURL+"/orders/{order-id}/trade", wrapper.GetOrdersOrderIdTrade)
	m.HandleFunc("POST "+options.BaseURL+"/orders/{order-id}/trade", wrapper.PostOrdersOrderIdTrade)
	m.HandleFunc("DELETE "+options.BaseURL+"/orders/{order-id}/trade/escrow", wrapper.DeleteOrdersOrderIdTradeEscrow)
	m.HandleFunc("GET "+options.BaseURL+"/orders/{order-id}/trade/escrow", wrapper.GetOrdersOrderIdTradeEscrow)
	m.HandleFunc("POST "+options.BaseURL+"/orders/{order-id}/trade/escrow", wrapper.PostOrdersOrderIdTradeEscrow)
	m.HandleFunc("DELETE "+options.BaseURL+"/orders/{order-id}/trade/escrow/dispute", wrapper.DeleteOrdersOrderIdTradeEscrowDispute)
	m.HandleFunc("POST "+options.BaseURL+"/orders/{order-id}/trade/escrow/dispute", wrapper.PostOrdersOrderIdTradeEscrowDispute)
	m.HandleFunc("POST "+options.BaseURL+"/token/generate", wrapper.PostTokenGenerate)

	return m
}

type GetOrdersRequestObject struct {
	Params GetOrdersParams
}

type GetOrdersResponseObject interface {
	VisitGetOrdersResponse(w http.ResponseWriter) error
}

type GetOrders200JSONResponse OrderArray

func (response GetOrders200JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostOrdersRequestObject struct {
	Body *PostOrdersJSONRequestBody
}

type PostOrdersResponseObject interface {
	VisitPostOrdersResponse(w http.ResponseWriter) error
}

type PostOrders201JSONResponse JSONMessage

func (response PostOrders201JSONResponse) VisitPostOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrdersOrderIdRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type DeleteOrdersOrderIdResponseObject interface {
	VisitDeleteOrdersOrderIdResponse(w http.ResponseWriter) error
}

type DeleteOrdersOrderId200JSONResponse JSONMessage

func (response DeleteOrdersOrderId200JSONResponse) VisitDeleteOrdersOrderIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrdersOrderIdRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type GetOrdersOrderIdResponseObject interface {
	VisitGetOrdersOrderIdResponse(w http.ResponseWriter) error
}

type GetOrdersOrderId200JSONResponse Order

func (response GetOrdersOrderId200JSONResponse) VisitGetOrdersOrderIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrdersOrderIdTradeRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type DeleteOrdersOrderIdTradeResponseObject interface {
	VisitDeleteOrdersOrderIdTradeResponse(w http.ResponseWriter) error
}

type DeleteOrdersOrderIdTrade200Response struct {
}

func (response DeleteOrdersOrderIdTrade200Response) VisitDeleteOrdersOrderIdTradeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetOrdersOrderIdTradeRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type GetOrdersOrderIdTradeResponseObject interface {
	VisitGetOrdersOrderIdTradeResponse(w http.ResponseWriter) error
}

type GetOrdersOrderIdTrade200Response struct {
}

func (response GetOrdersOrderIdTrade200Response) VisitGetOrdersOrderIdTradeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostOrdersOrderIdTradeRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type PostOrdersOrderIdTradeResponseObject interface {
	VisitPostOrdersOrderIdTradeResponse(w http.ResponseWriter) error
}

type PostOrdersOrderIdTrade200Response struct {
}

func (response PostOrdersOrderIdTrade200Response) VisitPostOrdersOrderIdTradeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteOrdersOrderIdTradeEscrowRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type DeleteOrdersOrderIdTradeEscrowResponseObject interface {
	VisitDeleteOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error
}

type DeleteOrdersOrderIdTradeEscrow200JSONResponse JSONMessage

func (response DeleteOrdersOrderIdTradeEscrow200JSONResponse) VisitDeleteOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrdersOrderIdTradeEscrow400Response struct {
}

func (response DeleteOrdersOrderIdTradeEscrow400Response) VisitDeleteOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteOrdersOrderIdTradeEscrow402Response struct {
}

func (response DeleteOrdersOrderIdTradeEscrow402Response) VisitDeleteOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(402)
	return nil
}

type DeleteOrdersOrderIdTradeEscrow404Response struct {
}

func (response DeleteOrdersOrderIdTradeEscrow404Response) VisitDeleteOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetOrdersOrderIdTradeEscrowRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type GetOrdersOrderIdTradeEscrowResponseObject interface {
	VisitGetOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error
}

type GetOrdersOrderIdTradeEscrow200JSONResponse struct {
	Status *string `json:"status,omitempty"`
}

func (response GetOrdersOrderIdTradeEscrow200JSONResponse) VisitGetOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrdersOrderIdTradeEscrow400Response struct {
}

func (response GetOrdersOrderIdTradeEscrow400Response) VisitGetOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetOrdersOrderIdTradeEscrow401Response struct {
}

func (response GetOrdersOrderIdTradeEscrow401Response) VisitGetOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetOrdersOrderIdTradeEscrow404Response struct {
}

func (response GetOrdersOrderIdTradeEscrow404Response) VisitGetOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostOrdersOrderIdTradeEscrowRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type PostOrdersOrderIdTradeEscrowResponseObject interface {
	VisitPostOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error
}

type PostOrdersOrderIdTradeEscrow201Response struct {
}

func (response PostOrdersOrderIdTradeEscrow201Response) VisitPostOrdersOrderIdTradeEscrowResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type DeleteOrdersOrderIdTradeEscrowDisputeRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type DeleteOrdersOrderIdTradeEscrowDisputeResponseObject interface {
	VisitDeleteOrdersOrderIdTradeEscrowDisputeResponse(w http.ResponseWriter) error
}

type DeleteOrdersOrderIdTradeEscrowDispute200Response struct {
}

func (response DeleteOrdersOrderIdTradeEscrowDispute200Response) VisitDeleteOrdersOrderIdTradeEscrowDisputeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostOrdersOrderIdTradeEscrowDisputeRequestObject struct {
	OrderId openapi_types.UUID `json:"order-id"`
}

type PostOrdersOrderIdTradeEscrowDisputeResponseObject interface {
	VisitPostOrdersOrderIdTradeEscrowDisputeResponse(w http.ResponseWriter) error
}

type PostOrdersOrderIdTradeEscrowDispute201Response struct {
}

func (response PostOrdersOrderIdTradeEscrowDispute201Response) VisitPostOrdersOrderIdTradeEscrowDisputeResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PostTokenGenerateRequestObject struct {
}

type PostTokenGenerateResponseObject interface {
	VisitPostTokenGenerateResponse(w http.ResponseWriter) error
}

type PostTokenGenerate201JSONResponse struct {
	Token *string `json:"token,omitempty"`
}

func (response PostTokenGenerate201JSONResponse) VisitPostTokenGenerateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /orders)
	GetOrders(ctx context.Context, request GetOrdersRequestObject) (GetOrdersResponseObject, error)

	// (POST /orders)
	PostOrders(ctx context.Context, request PostOrdersRequestObject) (PostOrdersResponseObject, error)

	// (DELETE /orders/{order-id})
	DeleteOrdersOrderId(ctx context.Context, request DeleteOrdersOrderIdRequestObject) (DeleteOrdersOrderIdResponseObject, error)

	// (GET /orders/{order-id})
	GetOrdersOrderId(ctx context.Context, request GetOrdersOrderIdRequestObject) (GetOrdersOrderIdResponseObject, error)

	// (DELETE /orders/{order-id}/trade)
	DeleteOrdersOrderIdTrade(ctx context.Context, request DeleteOrdersOrderIdTradeRequestObject) (DeleteOrdersOrderIdTradeResponseObject, error)

	// (GET /orders/{order-id}/trade)
	GetOrdersOrderIdTrade(ctx context.Context, request GetOrdersOrderIdTradeRequestObject) (GetOrdersOrderIdTradeResponseObject, error)

	// (POST /orders/{order-id}/trade)
	PostOrdersOrderIdTrade(ctx context.Context, request PostOrdersOrderIdTradeRequestObject) (PostOrdersOrderIdTradeResponseObject, error)

	// (DELETE /orders/{order-id}/trade/escrow)
	DeleteOrdersOrderIdTradeEscrow(ctx context.Context, request DeleteOrdersOrderIdTradeEscrowRequestObject) (DeleteOrdersOrderIdTradeEscrowResponseObject, error)

	// (GET /orders/{order-id}/trade/escrow)
	GetOrdersOrderIdTradeEscrow(ctx context.Context, request GetOrdersOrderIdTradeEscrowRequestObject) (GetOrdersOrderIdTradeEscrowResponseObject, error)

	// (POST /orders/{order-id}/trade/escrow)
	PostOrdersOrderIdTradeEscrow(ctx context.Context, request PostOrdersOrderIdTradeEscrowRequestObject) (PostOrdersOrderIdTradeEscrowResponseObject, error)

	// (DELETE /orders/{order-id}/trade/escrow/dispute)
	DeleteOrdersOrderIdTradeEscrowDispute(ctx context.Context, request DeleteOrdersOrderIdTradeEscrowDisputeRequestObject) (DeleteOrdersOrderIdTradeEscrowDisputeResponseObject, error)

	// (POST /orders/{order-id}/trade/escrow/dispute)
	PostOrdersOrderIdTradeEscrowDispute(ctx context.Context, request PostOrdersOrderIdTradeEscrowDisputeRequestObject) (PostOrdersOrderIdTradeEscrowDisputeResponseObject, error)

	// (POST /token/generate)
	PostTokenGenerate(ctx context.Context, request PostTokenGenerateRequestObject) (PostTokenGenerateResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetOrders operation middleware
func (sh *strictHandler) GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams) {
	var request GetOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrders(ctx, request.(GetOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersResponseObject); ok {
		if err := validResponse.VisitGetOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOrders operation middleware
func (sh *strictHandler) PostOrders(w http.ResponseWriter, r *http.Request) {
	var request PostOrdersRequestObject

	var body PostOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostOrders(ctx, request.(PostOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostOrdersResponseObject); ok {
		if err := validResponse.VisitPostOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrdersOrderId operation middleware
func (sh *strictHandler) DeleteOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request DeleteOrdersOrderIdRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrdersOrderId(ctx, request.(DeleteOrdersOrderIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrdersOrderId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrdersOrderIdResponseObject); ok {
		if err := validResponse.VisitDeleteOrdersOrderIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrdersOrderId operation middleware
func (sh *strictHandler) GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request GetOrdersOrderIdRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrdersOrderId(ctx, request.(GetOrdersOrderIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrdersOrderId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersOrderIdResponseObject); ok {
		if err := validResponse.VisitGetOrdersOrderIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrdersOrderIdTrade operation middleware
func (sh *strictHandler) DeleteOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request DeleteOrdersOrderIdTradeRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrdersOrderIdTrade(ctx, request.(DeleteOrdersOrderIdTradeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrdersOrderIdTrade")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrdersOrderIdTradeResponseObject); ok {
		if err := validResponse.VisitDeleteOrdersOrderIdTradeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrdersOrderIdTrade operation middleware
func (sh *strictHandler) GetOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request GetOrdersOrderIdTradeRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrdersOrderIdTrade(ctx, request.(GetOrdersOrderIdTradeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrdersOrderIdTrade")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersOrderIdTradeResponseObject); ok {
		if err := validResponse.VisitGetOrdersOrderIdTradeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOrdersOrderIdTrade operation middleware
func (sh *strictHandler) PostOrdersOrderIdTrade(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request PostOrdersOrderIdTradeRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostOrdersOrderIdTrade(ctx, request.(PostOrdersOrderIdTradeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOrdersOrderIdTrade")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostOrdersOrderIdTradeResponseObject); ok {
		if err := validResponse.VisitPostOrdersOrderIdTradeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrdersOrderIdTradeEscrow operation middleware
func (sh *strictHandler) DeleteOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request DeleteOrdersOrderIdTradeEscrowRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrdersOrderIdTradeEscrow(ctx, request.(DeleteOrdersOrderIdTradeEscrowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrdersOrderIdTradeEscrow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrdersOrderIdTradeEscrowResponseObject); ok {
		if err := validResponse.VisitDeleteOrdersOrderIdTradeEscrowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrdersOrderIdTradeEscrow operation middleware
func (sh *strictHandler) GetOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request GetOrdersOrderIdTradeEscrowRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrdersOrderIdTradeEscrow(ctx, request.(GetOrdersOrderIdTradeEscrowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrdersOrderIdTradeEscrow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersOrderIdTradeEscrowResponseObject); ok {
		if err := validResponse.VisitGetOrdersOrderIdTradeEscrowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOrdersOrderIdTradeEscrow operation middleware
func (sh *strictHandler) PostOrdersOrderIdTradeEscrow(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request PostOrdersOrderIdTradeEscrowRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostOrdersOrderIdTradeEscrow(ctx, request.(PostOrdersOrderIdTradeEscrowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOrdersOrderIdTradeEscrow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostOrdersOrderIdTradeEscrowResponseObject); ok {
		if err := validResponse.VisitPostOrdersOrderIdTradeEscrowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrdersOrderIdTradeEscrowDispute operation middleware
func (sh *strictHandler) DeleteOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request DeleteOrdersOrderIdTradeEscrowDisputeRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrdersOrderIdTradeEscrowDispute(ctx, request.(DeleteOrdersOrderIdTradeEscrowDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrdersOrderIdTradeEscrowDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrdersOrderIdTradeEscrowDisputeResponseObject); ok {
		if err := validResponse.VisitDeleteOrdersOrderIdTradeEscrowDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOrdersOrderIdTradeEscrowDispute operation middleware
func (sh *strictHandler) PostOrdersOrderIdTradeEscrowDispute(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request PostOrdersOrderIdTradeEscrowDisputeRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostOrdersOrderIdTradeEscrowDispute(ctx, request.(PostOrdersOrderIdTradeEscrowDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOrdersOrderIdTradeEscrowDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostOrdersOrderIdTradeEscrowDisputeResponseObject); ok {
		if err := validResponse.VisitPostOrdersOrderIdTradeEscrowDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostTokenGenerate operation middleware
func (sh *strictHandler) PostTokenGenerate(w http.ResponseWriter, r *http.Request) {
	var request PostTokenGenerateRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostTokenGenerate(ctx, request.(PostTokenGenerateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTokenGenerate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostTokenGenerateResponseObject); ok {
		if err := validResponse.VisitPostTokenGenerateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
